language: c

os:
  - linux

compiler:
  - gcc

sudo: required

dist: trusty

install:
  - sudo apt-get update
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

script:
  - make check CFLAGS="-std=gnu99 -fPIC -fprofile-arcs -ftest-coverage -g -O0"

after_success:
  - lcov -d . -b tests/static --capture --output-file coverage.info
  - coveralls-lcov coverage.info
